import React from 'react';
import { Download, RefreshCw, AlertCircle, CheckCircle2 } from 'lucide-react';
import { Button } from './Button';

interface ResultDisplayProps {
  resultImage: string | null;
  isLoading: boolean;
  error: string | null;
  onDownload: () => void;
}

export const ResultDisplay: React.FC<ResultDisplayProps> = ({ 
  resultImage, 
  isLoading, 
  error,
  onDownload
}) => {
  
  if (error) {
    return (
      <div className="w-full h-64 sm:h-80 md:h-96 rounded-2xl bg-red-900/10 border border-red-800/50 flex flex-col items-center justify-center p-6 text-center animate-in fade-in zoom-in duration-300">
        <div className="w-12 h-12 rounded-full bg-red-900/30 flex items-center justify-center mb-4">
          <AlertCircle className="w-6 h-6 text-red-400" />
        </div>
        <h3 className="text-lg font-semibold text-red-200 mb-2">Generation Failed</h3>
        <p className="text-sm text-red-300 max-w-xs">{error}</p>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="w-full h-64 sm:h-80 md:h-96 rounded-2xl bg-slate-800/50 border border-slate-700 flex flex-col items-center justify-center p-6 relative overflow-hidden">
        {/* Scanning Effect */}
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-indigo-500/10 to-transparent w-full h-full animate-[shimmer_2s_infinite] -translate-y-full" />
        
        <div className="relative z-10 flex flex-col items-center">
          <div className="w-16 h-16 rounded-full border-4 border-indigo-500/30 border-t-indigo-500 animate-spin mb-6"></div>
          <h3 className="text-lg font-semibold text-white mb-2">AI is working its magic...</h3>
          <p className="text-sm text-slate-400 text-center max-w-xs">
            Analyzing facial features and applying professional styling. This usually takes about 5-10 seconds.
          </p>
        </div>
      </div>
    );
  }

  if (!resultImage) {
    return (
      <div className="w-full h-64 sm:h-80 md:h-96 rounded-2xl bg-slate-800/30 border border-slate-700/50 border-dashed flex flex-col items-center justify-center p-6 text-center">
        <div className="w-16 h-16 rounded-full bg-slate-800 flex items-center justify-center mb-4 opacity-50">
          <RefreshCw className="w-8 h-8 text-slate-500" />
        </div>
        <p className="text-slate-500">Your professional headshot will appear here.</p>
      </div>
    );
  }

  return (
    <div className="group relative w-full h-64 sm:h-80 md:h-96 rounded-2xl overflow-hidden bg-slate-900 border-2 border-indigo-500/50 shadow-[0_0_30px_rgba(99,102,241,0.15)] animate-in fade-in zoom-in duration-500">
      <img 
        src={resultImage} 
        alt="AI Generated Headshot" 
        className="w-full h-full object-contain bg-black/40"
      />
      
      <div className="absolute top-4 left-4 px-3 py-1 bg-indigo-600/90 backdrop-blur-sm rounded-full text-xs font-medium text-white shadow-lg flex items-center">
        <CheckCircle2 className="w-3 h-3 mr-1.5" />
        Generated by Gemini
      </div>

      <div className="absolute inset-x-0 bottom-0 p-6 bg-gradient-to-t from-black/90 via-black/60 to-transparent translate-y-full group-hover:translate-y-0 transition-transform duration-300 flex items-end justify-center">
        <Button 
          onClick={onDownload} 
          variant="primary" 
          className="w-full shadow-xl"
          icon={<Download className="w-4 h-4" />}
        >
          Download Headshot
        </Button>
      </div>
    </div>
  );
};